//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BassoLegnami.Resources.Models
{
    using System;


    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource()
        {
        }

        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BassoLegnami.Resources.Models.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Aggiungi.
        /// </summary>
        public static string Add
        {
            get
            {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Aggiungi nuovo.
        /// </summary>
        public static string AddNew
        {
            get
            {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Amministrazione.
        /// </summary>
        public static string Administration
        {
            get
            {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Tutti.
        /// </summary>
        public static string All
        {
            get
            {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tutti.
        /// </summary>
        public static string InvalidLoginAttempt
        {
            get
            {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Indietro.
        /// </summary>
        public static string Back
        {
            get
            {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Elenco.
        /// </summary>
        public static string BackToList
        {
            get
            {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Chiudi.
        /// </summary>
        public static string Close
        {
            get
            {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Conferma.
        /// </summary>
        public static string Confirm
        {
            get
            {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Cessazioni contratti.
        /// </summary>
        public static string ContractExpiryReasonsObject
        {
            get
            {
                return ResourceManager.GetString("ContractExpiryReasonsObject", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Crea.
        /// </summary>
        public static string Create
        {
            get
            {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Crea nuovo.
        /// </summary>
        public static string CreateNew
        {
            get
            {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Elimina.
        /// </summary>
        public static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Confermi l&apos;eliminazione del record?.
        /// </summary>
        public static string DeleteConfirm
        {
            get
            {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Dettagli.
        /// </summary>
        public static string Details
        {
            get
            {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Modifica.
        /// </summary>
        public static string Edit
        {
            get
            {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Somministrazione corsi.
        /// </summary>
        public static string EmployeeCoursesObject
        {
            get
            {
                return ResourceManager.GetString("EmployeeCoursesObject", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Sistema esterno.
        /// </summary>
        public static string ExternalSystemsObject
        {
            get
            {
                return ResourceManager.GetString("ExternalSystemsObject", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a SE.
        /// </summary>
        public static string ExternalSystemsObjectInitial
        {
            get
            {
                return ResourceManager.GetString("ExternalSystemsObjectInitial", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Valori sistemi esterni.
        /// </summary>
        public static string ExternalSystemValuesObject
        {
            get
            {
                return ResourceManager.GetString("ExternalSystemValuesObject", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a VE.
        /// </summary>
        public static string ExternalSystemValuesObjectInitial
        {
            get
            {
                return ResourceManager.GetString("ExternalSystemValuesObjectInitial", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserire il valore con estensione valida.
        /// </summary>
        public static string FieldAccetpInvalid
        {
            get
            {
                return ResourceManager.GetString("FieldAccetpInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Numero di carta di credito non valido.
        /// </summary>
        public static string FieldCreditCardInvalid
        {
            get
            {
                return ResourceManager.GetString("FieldCreditCardInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Data non valida.
        /// </summary>
        public static string FieldDateInvalid
        {
            get
            {
                return ResourceManager.GetString("FieldDateInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Indirizzo email non valido.
        /// </summary>
        public static string FieldEmailInvalid
        {
            get
            {
                return ResourceManager.GetString("FieldEmailInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserire nuovamente lo stesso valore.
        /// </summary>
        public static string FieldEqualTo
        {
            get
            {
                return ResourceManager.GetString("FieldEqualTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserire un valore minore o uguale a {0}.
        /// </summary>
        public static string FieldMax
        {
            get
            {
                return ResourceManager.GetString("FieldMax", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserire al massimo {0} caratteri.
        /// </summary>
        public static string FieldMaxLength
        {
            get
            {
                return ResourceManager.GetString("FieldMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserire un valore maggiore o uguale a {0}.
        /// </summary>
        public static string FieldMin
        {
            get
            {
                return ResourceManager.GetString("FieldMin", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserire almeno {0} caratteri.
        /// </summary>
        public static string FieldMinLength
        {
            get
            {
                return ResourceManager.GetString("FieldMinLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Numero non valido.
        /// </summary>
        public static string FieldNumberInvalid
        {
            get
            {
                return ResourceManager.GetString("FieldNumberInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserire solo numeri.
        /// </summary>
        public static string FieldOnlyDigits
        {
            get
            {
                return ResourceManager.GetString("FieldOnlyDigits", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserire un valore compreso tra {0} e {1}.
        /// </summary>
        public static string FieldRange
        {
            get
            {
                return ResourceManager.GetString("FieldRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserire un valore compreso tra {0} e {1} caratteri di lunghezza.
        /// </summary>
        public static string FieldRangeLength
        {
            get
            {
                return ResourceManager.GetString("FieldRangeLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Correggere il campo.
        /// </summary>
        public static string FieldRemote
        {
            get
            {
                return ResourceManager.GetString("FieldRemote", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Campo obbligatorio.
        /// </summary>
        public static string FieldRequired
        {
            get
            {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Indirizzo non valido.
        /// </summary>
        public static string FieldURLInvalid
        {
            get
            {
                return ResourceManager.GetString("FieldURLInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Da.
        /// </summary>
        public static string From
        {
            get
            {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Dati generali.
        /// </summary>
        public static string GeneralTab
        {
            get
            {
                return ResourceManager.GetString("GeneralTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Home.
        /// </summary>
        public static string Home
        {
            get
            {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a (filtrati su _MAX_ record).
        /// </summary>
        public static string InfoFiltered
        {
            get
            {
                return ResourceManager.GetString("InfoFiltered", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Valore {0} non valido.
        /// </summary>
        public static string InvalidValue
        {
            get
            {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Elenco.
        /// </summary>
        public static string List
        {
            get
            {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Logout.
        /// </summary>
        public static string LogOut
        {
            get
            {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Anagrafiche.
        /// </summary>
        public static string Main
        {
            get
            {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Il campo {0} deve avere una lunghezza massima di {1}..
        /// </summary>
        public static string MaxLength
        {
            get
            {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessun record disponibile.
        /// </summary>
        public static string NoData
        {
            get
            {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Note.
        /// </summary>
        public static string Note
        {
            get
            {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Record _START_ / _END_ di _TOTAL_.
        /// </summary>
        public static string PaginationInfo
        {
            get
            {
                return ResourceManager.GetString("PaginationInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Mostra _MENU_ record/pagina.
        /// </summary>
        public static string PaginationSelector
        {
            get
            {
                return ResourceManager.GetString("PaginationSelector", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Modalità di pagamento.
        /// </summary>
        public static string PaymentMethodsObject
        {
            get
            {
                return ResourceManager.GetString("PaymentMethodsObject", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a MP.
        /// </summary>
        public static string PaymentMethodsObjectInitial
        {
            get
            {
                return ResourceManager.GetString("PaymentMethodsObjectInitial", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Il campo {0} deve avere un valore compreso tra {1} e {2}..
        /// </summary>
        public static string Range
        {
            get
            {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Rimuovi.
        /// </summary>
        public static string Remove
        {
            get
            {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Salva.
        /// </summary>
        public static string Save
        {
            get
            {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Ricerca:.
        /// </summary>
        public static string SearchBy
        {
            get
            {
                return ResourceManager.GetString("SearchBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Ricerca record.
        /// </summary>
        public static string SearchRecords
        {
            get
            {
                return ResourceManager.GetString("SearchRecords", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Selezionare un valore.
        /// </summary>
        public static string SelectValue
        {
            get
            {
                return ResourceManager.GetString("SelectValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Impostazioni.
        /// </summary>
        public static string SettingsObject
        {
            get
            {
                return ResourceManager.GetString("SettingsObject", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a I.
        /// </summary>
        public static string SettingsObjectInitial
        {
            get
            {
                return ResourceManager.GetString("SettingsObjectInitial", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Supporto.
        /// </summary>
        public static string Support
        {
            get
            {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a A.
        /// </summary>
        public static string To
        {
            get
            {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Unità di Misura.
        /// </summary>
        public static string UnitOfMeasurementsObject
        {
            get
            {
                return ResourceManager.GetString("UnitOfMeasurementsObject", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a UM.
        /// </summary>
        public static string UnitOfMeasurementsObjectInitial
        {
            get
            {
                return ResourceManager.GetString("UnitOfMeasurementsObjectInitial", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Utenti.
        /// </summary>
        public static string Users
        {
            get
            {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a Utenti.
        /// </summary>
        public static string UsersObject
        {
            get
            {
                return ResourceManager.GetString("UsersObject", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string UsersObjectInitial
        {
            get
            {
                return ResourceManager.GetString("UsersObjectInitial", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Presence
        {
            get
            {
                return ResourceManager.GetString("Presence", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Absence
        {
            get
            {
                return ResourceManager.GetString("Absence", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Road
        {
            get
            {
                return ResourceManager.GetString("Road", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Courtyard
        {
            get
            {
                return ResourceManager.GetString("Courtyard", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string OneSwingWithGlass
        {
            get
            {
                return ResourceManager.GetString("OneSwingWithGlass", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string TwoSwingsWithGlass
        {
            get
            {
                return ResourceManager.GetString("TwoSwingsWithGlass", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string OneSwingWithoutGlass
        {
            get
            {
                return ResourceManager.GetString("OneSwingWithoutGlass", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string TwoSwingsWithoutGlass
        {
            get
            {
                return ResourceManager.GetString("TwoSwingsWithoutGlass", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Safe
        {
            get
            {
                return ResourceManager.GetString("Safe", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Unsafe
        {
            get
            {
                return ResourceManager.GetString("Unsafe", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Fixed
        {
            get
            {
                return ResourceManager.GetString("Fixed", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Nonslip
        {
            get
            {
                return ResourceManager.GetString("Nonslip", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string BuitIn
        {
            get
            {
                return ResourceManager.GetString("BuitIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Yes
        {
            get
            {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string No
        {
            get
            {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Shared
        {
            get
            {
                return ResourceManager.GetString("Shared", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Other
        {
            get
            {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string PrivacyCompliant
        {
            get
            {
                return ResourceManager.GetString("PrivacyCompliant", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NonPrivacyCompliant
        {
            get
            {
                return ResourceManager.GetString("NonPrivacyCompliant", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Compliant
        {
            get
            {
                return ResourceManager.GetString("Compliant", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NonCompliant
        {
            get
            {
                return ResourceManager.GetString("NonCompliant", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string InternalSecurity
        {
            get
            {
                return ResourceManager.GetString("InternalSecurity", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string ExternalSecurity
        {
            get
            {
                return ResourceManager.GetString("ExternalSecurity", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Good
        {
            get
            {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string BrokenOrUnsafe
        {
            get
            {
                return ResourceManager.GetString("BrokenOrUnsafe", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Likely
        {
            get
            {
                return ResourceManager.GetString("Likely", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Unlikely
        {
            get
            {
                return ResourceManager.GetString("Unlikely", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Excluded
        {
            get
            {
                return ResourceManager.GetString("Excluded", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Regular
        {
            get
            {
                return ResourceManager.GetString("Regular", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NotRegular
        {
            get
            {
                return ResourceManager.GetString("NotRegular", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string GreaterThan120
        {
            get
            {
                return ResourceManager.GetString("GreaterThan120", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string LessThan120
        {
            get
            {
                return ResourceManager.GetString("LessThan120", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string GreaterThan100
        {
            get
            {
                return ResourceManager.GetString("GreaterThan100", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string LessThan100
        {
            get
            {
                return ResourceManager.GetString("LessThan100", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string RegularParapet
        {
            get
            {
                return ResourceManager.GetString("RegularParapet", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NotRegularParapet
        {
            get
            {
                return ResourceManager.GetString("NotRegularParapet", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string GreaterThan30
        {
            get
            {
                return ResourceManager.GetString("GreaterThan30", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string LessThan30
        {
            get
            {
                return ResourceManager.GetString("LessThan30", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string BadStateBeenStep
        {
            get
            {
                return ResourceManager.GetString("BadStateBeenStep", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string GoodStateBeenStep
        {
            get
            {
                return ResourceManager.GetString("GoodStateBeenStep", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string OneSide
        {
            get
            {
                return ResourceManager.GetString("OneSide", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string TwoSides
        {
            get
            {
                return ResourceManager.GetString("TwoSides", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string SufficientLighting
        {
            get
            {
                return ResourceManager.GetString("SufficientLighting", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string InsufficientLighting
        {
            get
            {
                return ResourceManager.GetString("InsufficientLighting", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string BrokenStructure
        {
            get
            {
                return ResourceManager.GetString("BrokenStructure", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string GoodCondictionStructure
        {
            get
            {
                return ResourceManager.GetString("GoodCondictionStructure", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string RampStartSigned
        {
            get
            {
                return ResourceManager.GetString("RampStartSigned", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string RampStartNotSigned
        {
            get
            {
                return ResourceManager.GetString("RampStartNotSigned", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string RampEndSigned
        {
            get
            {
                return ResourceManager.GetString("RampEndSigned", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string RampEndNotSigned
        {
            get
            {
                return ResourceManager.GetString("RampEndNotSigned", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string GoodCondictionStucture
        {
            get
            {
                return ResourceManager.GetString("GoodCondictionStucture", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Advice
        {
            get
            {
                return ResourceManager.GetString("Advice", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string BadCondictionStucture
        {
            get
            {
                return ResourceManager.GetString("BadCondictionStucture", resourceCulture);
            }
        }
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string UndamagedBox
        {
            get
            {
                return ResourceManager.GetString("UndamagedBox", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string BrokenBox
        {
            get
            {
                return ResourceManager.GetString("BrokenBox", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Security
        {
            get
            {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NotSecurity
        {
            get
            {
                return ResourceManager.GetString("NotSecurity", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Sure
        {
            get
            {
                return ResourceManager.GetString("Sure", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NotSure
        {
            get
            {
                return ResourceManager.GetString("NotSure", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Present
        {
            get
            {
                return ResourceManager.GetString("Present", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Presents
        {
            get
            {
                return ResourceManager.GetString("Presents", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NotPresent
        {
            get
            {
                return ResourceManager.GetString("NotPresent", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NotPresents
        {
            get
            {
                return ResourceManager.GetString("NotPresents", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string PavimentFixed
        {
            get
            {
                return ResourceManager.GetString("PavimentFixed", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string AntiSlip
        {
            get
            {
                return ResourceManager.GetString("AntiSlip", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Incassed
        {
            get
            {
                return ResourceManager.GetString("Incassed", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string AccessAtticDoor
        {
            get
            {
                return ResourceManager.GetString("AccessAtticDoor", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string AccessAtticManhole
        {
            get
            {
                return ResourceManager.GetString("AccessAtticManhole", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string AuthorizedPersons
        {
            get
            {
                return ResourceManager.GetString("AuthorizedPersons", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string AuthorizedToAll
        {
            get
            {
                return ResourceManager.GetString("AuthorizedToAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string OpenSecurity
        {
            get
            {
                return ResourceManager.GetString("OpenSecurity", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string CloseSecurity
        {
            get
            {
                return ResourceManager.GetString("CloseSecurity", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NA
        {
            get
            {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string LowQuantity
        {
            get
            {
                return ResourceManager.GetString("LowQuantity", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string MediumQuantity
        {
            get
            {
                return ResourceManager.GetString("MediumQuantity", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string HighQuantity
        {
            get
            {
                return ResourceManager.GetString("HighQuantity", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Deepen
        {
            get
            {
                return ResourceManager.GetString("Deepen", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string CustomSecurity
        {
            get
            {
                return ResourceManager.GetString("CustomSecurity", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string CustomSlip
        {
            get
            {
                return ResourceManager.GetString("CustomSlip", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string CustomBuitln
        {
            get
            {
                return ResourceManager.GetString("CustomBuitln", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string DoorWithGlass
        {
            get
            {
                return ResourceManager.GetString("DoorWithGlass", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string TwoDoorWithGlass
        {
            get
            {
                return ResourceManager.GetString("TwoDoorWithGlass", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string DoorWithoutGlass
        {
            get
            {
                return ResourceManager.GetString("DoorWithoutGlass", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string TwoDoorWithoutGlass
        {
            get
            {
                return ResourceManager.GetString("TwoDoorWithoutGlass", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Higher
        {
            get
            {
                return ResourceManager.GetString("Higher", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Inferior
        {
            get
            {
                return ResourceManager.GetString("Inferior", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string EqualOrGreater30
        {
            get
            {
                return ResourceManager.GetString("EqualOrGreater30", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Inferior30
        {
            get
            {
                return ResourceManager.GetString("Inferior30", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string GoodCondition
        {
            get
            {
                return ResourceManager.GetString("GoodCondition", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string DamageItem
        {
            get
            {
                return ResourceManager.GetString("DamageItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NotSureMaterial
        {
            get
            {
                return ResourceManager.GetString("NotSureMaterial", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NotSureObstacles
        {
            get
            {
                return ResourceManager.GetString("NotSureObstacles", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string AbsenceItem
        {
            get
            {
                return ResourceManager.GetString("AbsenceItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string PresenceItem
        {
            get
            {
                return ResourceManager.GetString("PresenceItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Insecurities
        {
            get
            {
                return ResourceManager.GetString("Insecurities", resourceCulture);
            }
        }
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Incomplete
        {
            get
            {
                return ResourceManager.GetString("Incomplete", resourceCulture);
            }
        }
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string DistrictHeating
        {
            get
            {
                return ResourceManager.GetString("DistrictHeating", resourceCulture);
            }
        }
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Accordant
        {
            get
            {
                return ResourceManager.GetString("Accordant", resourceCulture);
            }
        }
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NotAccordant
        {
            get
            {
                return ResourceManager.GetString("NotAccordant", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string CarriedOut
        {
            get
            {
                return ResourceManager.GetString("CarriedOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NotCarriedOut
        {
            get
            {
                return ResourceManager.GetString("NotCarriedOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Door2Swing
        {
            get
            {
                return ResourceManager.GetString("Door2Swing", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string DoorWay2Swing
        {
            get
            {
                return ResourceManager.GetString("DoorWay2Swing", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string ManualGate
        {
            get
            {
                return ResourceManager.GetString("ManualGate", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string AutomaticGate
        {
            get
            {
                return ResourceManager.GetString("AutomaticGate", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string ToBeVerified
        {
            get
            {
                return ResourceManager.GetString("ToBeVerified", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Flat
        {
            get
            {
                return ResourceManager.GetString("Flat", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Gradients5
        {
            get
            {
                return ResourceManager.GetString("Gradients5", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string UpperSlopes5
        {
            get
            {
                return ResourceManager.GetString("UpperSlopes5", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string SignalPresent
        {
            get
            {
                return ResourceManager.GetString("SignalPresent", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NotSignalPresent
        {
            get
            {
                return ResourceManager.GetString("NotSignalPresent", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Greater100cm
        {
            get
            {
                return ResourceManager.GetString("Greater100cm", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Less100cm
        {
            get
            {
                return ResourceManager.GetString("Less100cm", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Compliance10cm
        {
            get
            {
                return ResourceManager.GetString("Compliance10cm", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NotCompliance10cm
        {
            get
            {
                return ResourceManager.GetString("NotCompliance10cm", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Appropriate
        {
            get
            {
                return ResourceManager.GetString("Appropriate", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NotAppropriate
        {
            get
            {
                return ResourceManager.GetString("NotAppropriate", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string SlopesLess5
        {
            get
            {
                return ResourceManager.GetString("SlopesLess5", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string SlopesGreater5
        {
            get
            {
                return ResourceManager.GetString("SlopesGreater5", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Suitable
        {
            get
            {
                return ResourceManager.GetString("Suitable", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Dangerous
        {
            get
            {
                return ResourceManager.GetString("Dangerous", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string MaintenancePresent
        {
            get
            {
                return ResourceManager.GetString("MaintenancePresent", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string MaintenanceAbsence
        {
            get
            {
                return ResourceManager.GetString("MaintenanceAbsence", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Forbidden
        {
            get
            {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Goods
        {
            get
            {
                return ResourceManager.GetString("Goods", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NotGood
        {
            get
            {
                return ResourceManager.GetString("NotGood", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Allowed
        {
            get
            {
                return ResourceManager.GetString("Allowed", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NotSuitable
        {
            get
            {
                return ResourceManager.GetString("NotSuitable", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string FreeObstacles
        {
            get
            {
                return ResourceManager.GetString("FreeObstacles", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Obstacle
        {
            get
            {
                return ResourceManager.GetString("Obstacle", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string MaterialPresent
        {
            get
            {
                return ResourceManager.GetString("MaterialPresent", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string LedgeWalls
        {
            get
            {
                return ResourceManager.GetString("LedgeWalls", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string LessThan300
        {
            get
            {
                return ResourceManager.GetString("LessThan300", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Integrated
        {
            get
            {
                return ResourceManager.GetString("Integrated", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string UnsuitableWindows
        {
            get
            {
                return ResourceManager.GetString("UnsuitableWindows", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Between300And1000
        {
            get
            {
                return ResourceManager.GetString("Between300And1000", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Between1000And3000
        {
            get
            {
                return ResourceManager.GetString("Between1000And3000", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Over3000
        {
            get
            {
                return ResourceManager.GetString("Over3000", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Emergency
        {
            get
            {
                return ResourceManager.GetString("Emergency", resourceCulture);
            }
        }


        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string ExternalAccess
        {
            get
            {
                return ResourceManager.GetString("ExternalAccess", resourceCulture);
            }
        }


        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string InternAccess
        {
            get
            {
                return ResourceManager.GetString("InternAccess", resourceCulture);
            }
        }


        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string PresentRegolarMaintenance
        {
            get
            {
                return ResourceManager.GetString("PresentRegolarMaintenance", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string InsufficientMaintenance
        {
            get
            {
                return ResourceManager.GetString("InsufficientMaintenance", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string AvaibleDocumentation
        {
            get
            {
                return ResourceManager.GetString("AvaibleDocumentation", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string SummayAnomalies
        {
            get
            {
                return ResourceManager.GetString("SummayAnomalies", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Entrance
        {
            get
            {
                return ResourceManager.GetString("Entrance", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Ladder
        {
            get
            {
                return ResourceManager.GetString("Ladder", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string StairsAndCorridors
        {
            get
            {
                return ResourceManager.GetString("StairsAndCorridors", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string CommonAttic
        {
            get
            {
                return ResourceManager.GetString("CommonAttic", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Cellars
        {
            get
            {
                return ResourceManager.GetString("Cellars", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string TechnicalRoom
        {
            get
            {
                return ResourceManager.GetString("TechnicalRoom", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string SolarLastric
        {
            get
            {
                return ResourceManager.GetString("SolarLastric", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string ConciergeRoom
        {
            get
            {
                return ResourceManager.GetString("ConciergeRoom", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Laundry
        {
            get
            {
                return ResourceManager.GetString("Laundry", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string ServiceArea
        {
            get
            {
                return ResourceManager.GetString("ServiceArea", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string CourtyardState
        {
            get
            {
                return ResourceManager.GetString("CourtyardState", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Parking
        {
            get
            {
                return ResourceManager.GetString("Parking", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string GreenAreas
        {
            get
            {
                return ResourceManager.GetString("GreenAreas", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string GameAreas
        {
            get
            {
                return ResourceManager.GetString("GameAreas", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Garage
        {
            get
            {
                return ResourceManager.GetString("Garage", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string EchologicalArea
        {
            get
            {
                return ResourceManager.GetString("EchologicalArea", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string BuildingInterior
        {
            get
            {
                return ResourceManager.GetString("BuildingInterior", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string OutsideBuilding
        {
            get
            {
                return ResourceManager.GetString("OutsideBuilding", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Number
        {
            get
            {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string DocumentType
        {
            get
            {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Anomaly
        {
            get
            {
                return ResourceManager.GetString("Anomaly", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string PresenceSingular
        {
            get
            {
                return ResourceManager.GetString("PresenceSingular", resourceCulture);
            }
        }
       
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string AbsenceSingular
        {
            get
            {
                return ResourceManager.GetString("AbsenceSingular", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string PresenceGeneric
        {
            get
            {
                return ResourceManager.GetString("PresenceGeneric", resourceCulture);
            }
        }
       
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string AbsenceGeneric
        {
            get
            {
                return ResourceManager.GetString("AbsenceGeneric", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string CompliantPlural
        {
            get
            {
                return ResourceManager.GetString("CompliantPlural", resourceCulture);
            }
        }
       
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NonCompliantPlural
        {
            get
            {
                return ResourceManager.GetString("NonCompliantPlural", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string EqualOrGreater90
        {
            get
            {
                return ResourceManager.GetString("EqualOrGreater90", resourceCulture);
            }
        }
       
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string LessThan90
        {
            get
            {
                return ResourceManager.GetString("LessThan90", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string UndamagedLightingStructure
        {
            get
            {
                return ResourceManager.GetString("UndamagedLightingStructure", resourceCulture);
            }
        }
       
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string DamagedLightingStructure
        {
            get
            {
                return ResourceManager.GetString("DamagedLightingStructure", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NotSecurityLess1m
        {
            get
            {
                return ResourceManager.GetString("NotSecurityLess1m", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string IsPresent
        {
            get
            {
                return ResourceManager.GetString("IsPresent", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NotIsPresent
        {
            get
            {
                return ResourceManager.GetString("NotIsPresent", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string AbsentPlural
        {
            get
            {
                return ResourceManager.GetString("AbsentPlural", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string PresentPlural
        {
            get
            {
                return ResourceManager.GetString("PresentPlural", resourceCulture);
            }
        }
       
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string ExcludedFemale
        {
            get
            {
                return ResourceManager.GetString("ExcludedFemale", resourceCulture);
            }
        }
       
       
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string PresentSingular
        {
            get
            {
                return ResourceManager.GetString("PresentSingular", resourceCulture);
            }
        }
       
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string VideoMonitoringSystemInternal
        {
            get
            {
                return ResourceManager.GetString("VideoMonitoringSystemInternal", resourceCulture);
            }
        }
       
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string VideoMonitoringSystemExternal
        {
            get
            {
                return ResourceManager.GetString("VideoMonitoringSystemExternal", resourceCulture);
            }
        }
       
       
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string UnsafeSingular
        {
            get
            {
                return ResourceManager.GetString("UnsafeSingular", resourceCulture);
            }
        }
       
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string SafeSingular
        {
            get
            {
                return ResourceManager.GetString("SafeSingular", resourceCulture);
            }
        }
       
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string BrokenStructureFemale
        {
            get
            {
                return ResourceManager.GetString("BrokenStructureFemale", resourceCulture);
            }
        }
       
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string SuitablePlural
        {
            get
            {
                return ResourceManager.GetString("SuitablePlural", resourceCulture);
            }
        }
       
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NotSuitablePlural
        {
            get
            {
                return ResourceManager.GetString("NotSuitablePlural", resourceCulture);
            }
        }
       
       
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string DamageItemFemale
        {
            get
            {
                return ResourceManager.GetString("DamageItemFemale", resourceCulture);
            }
        }
       
       
       
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string LowQuantityPlural
        {
            get
            {
                return ResourceManager.GetString("LowQuantityPlural", resourceCulture);
            }
        }
       
       
       
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string MediumQuantityPlural
        {
            get
            {
                return ResourceManager.GetString("MediumQuantityPlural", resourceCulture);
            }
        }
       
       
       
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string HighQuantityPlural
        {
            get
            {
                return ResourceManager.GetString("HighQuantityPlural", resourceCulture);
            }
        }
       
       
       
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string VideoMonitoringSystemAccessBuilding
        {
            get
            {
                return ResourceManager.GetString("VideoMonitoringSystemAccessBuilding", resourceCulture);
            }
        }
       
       
       
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string VideoMonitoringSystemAccessParking
        {
            get
            {
                return ResourceManager.GetString("VideoMonitoringSystemAccessParking", resourceCulture);
            }
        }
       
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string AbsentSingular
        {
            get
            {
                return ResourceManager.GetString("AbsentSingular", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NotApplicable
        {
            get
            {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string SafeFemale
        {
            get
            {
                return ResourceManager.GetString("SafeFemale", resourceCulture);
            }
        }
       
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NotSafeFemale
        {
            get
            {
                return ResourceManager.GetString("NotSafeFemale", resourceCulture);
            }
        }


        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string TwoSidesNumber
        {
            get
            {
                return ResourceManager.GetString("TwoSidesNumber", resourceCulture);
            }
        }


        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Sign
        {
            get
            {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Total
        {
            get
            {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }


        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string AttachedFiles
        {
            get
            {
                return ResourceManager.GetString("AttachedFiles", resourceCulture);
            }
        }


        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Cancel
        {
            get
            {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }


        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string File
        {
            get
            {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }


        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string CreatedOn
        {
            get
            {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }


        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string IsValid
        {
            get
            {
                return ResourceManager.GetString("IsValid", resourceCulture);
            }
        }


        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string View
        {
            get
            {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }


        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Warning
        {
            get
            {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }


        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string UnauthorizedUser
        {
            get
            {
                return ResourceManager.GetString("UnauthorizedUser", resourceCulture);
            }

        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Search
        {
            get
            {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NoSearchResult
        {
            get
            {
                return ResourceManager.GetString("NoSearchResult", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Browse
        {
            get
            {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string ZipFileDownload
        {
            get
            {
                return ResourceManager.GetString("ZipFileDownload", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string AddFile
        {
            get
            {
                return ResourceManager.GetString("AddFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string QualifiedWorker
        {
            get
            {
                return ResourceManager.GetString("QualifiedWorker", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string SkilledWorker
        {
            get
            {
                return ResourceManager.GetString("SkilledWorker", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string EditPriceList
        {
            get
            {
                return ResourceManager.GetString("EditPriceList", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string SavePriceList
        {
            get
            {
                return ResourceManager.GetString("SavePriceList", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string SaveAsDraft
        {
            get
            {
                return ResourceManager.GetString("SaveAsDraft", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string SaveAndSend
        {
            get
            {
                return ResourceManager.GetString("SaveAndSend", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Head
        {
            get
            {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string NewFile
        {
            get
            {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string RequiredFieldLabel
        {
            get
            {
                return ResourceManager.GetString("RequiredFieldLabel", resourceCulture);
            }
        }


        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string FullCost
        {
            get
            {
                return ResourceManager.GetString("FullCost", resourceCulture);
            }
        }


        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string EmailSend
        {
            get
            {
                return ResourceManager.GetString("EmailSend", resourceCulture);
            }
        }


        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Order
        {
            get
            {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }


        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string Danger
        {
            get
            {
                return ResourceManager.GetString("Danger", resourceCulture);
            }
        }


        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string BackToHomePage
        {
            get
            {
                return ResourceManager.GetString("BackToHomePage", resourceCulture);
            }
        }


        /// <summary>
        ///   Cerca una stringa localizzata simile a U.
        /// </summary>
        public static string BackToCompany
        {
            get
            {
                return ResourceManager.GetString("BackToCompany", resourceCulture);
            }
        }



    }
}
