//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BassoLegnami.Model.Resources.Models.Support.AgentiGiacenze {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AgentiGiacenze {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AgentiGiacenze() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BassoLegnami.Model.Resources.Models.Support.AgentiGiacenze.AgentiGiacenze", typeof(AgentiGiacenze).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Certificazione.
        /// </summary>
        public static string Certificazione {
            get {
                return ResourceManager.GetString("Certificazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Classifica.
        /// </summary>
        public static string Classifica {
            get {
                return ResourceManager.GetString("Classifica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cliente Impegno.
        /// </summary>
        public static string ClienteImpegno {
            get {
                return ResourceManager.GetString("ClienteImpegno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data Impegno.
        /// </summary>
        public static string DataImpegno {
            get {
                return ResourceManager.GetString("DataImpegno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data Vendita.
        /// </summary>
        public static string DataVendita {
            get {
                return ResourceManager.GetString("DataVendita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Deposito.
        /// </summary>
        public static string Deposito {
            get {
                return ResourceManager.GetString("Deposito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dim1.
        /// </summary>
        public static string Dim1 {
            get {
                return ResourceManager.GetString("Dim1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dim2.
        /// </summary>
        public static string Dim2 {
            get {
                return ResourceManager.GetString("Dim2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dim3.
        /// </summary>
        public static string Dim3 {
            get {
                return ResourceManager.GetString("Dim3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Essenza.
        /// </summary>
        public static string Essenza {
            get {
                return ResourceManager.GetString("Essenza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fornitore.
        /// </summary>
        public static string Fornitore {
            get {
                return ResourceManager.GetString("Fornitore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lunghezza Descrizione.
        /// </summary>
        public static string LunghezzaDescr {
            get {
                return ResourceManager.GetString("LunghezzaDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Marchio.
        /// </summary>
        public static string Marchio {
            get {
                return ResourceManager.GetString("Marchio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Misura.
        /// </summary>
        public static string Misura {
            get {
                return ResourceManager.GetString("Misura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Numero pacchi.
        /// </summary>
        public static string NPackList {
            get {
                return ResourceManager.GetString("NPackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a NumeroCarico.
        /// </summary>
        public static string NumeroCarico {
            get {
                return ResourceManager.GetString("NumeroCarico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pacco.
        /// </summary>
        public static string Pacco {
            get {
                return ResourceManager.GetString("Pacco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Prezzo Acquisto.
        /// </summary>
        public static string PrezzoAcquisto {
            get {
                return ResourceManager.GetString("PrezzoAcquisto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Provenienza.
        /// </summary>
        public static string Provenienza {
            get {
                return ResourceManager.GetString("Provenienza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Qualità.
        /// </summary>
        public static string Qualita {
            get {
                return ResourceManager.GetString("Qualita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Quantità.
        /// </summary>
        public static string Quantita {
            get {
                return ResourceManager.GetString("Quantita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Quantità Venduta.
        /// </summary>
        public static string QuantitaVenduta {
            get {
                return ResourceManager.GetString("QuantitaVenduta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stagionatura.
        /// </summary>
        public static string Stagionatura {
            get {
                return ResourceManager.GetString("Stagionatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stato Legno.
        /// </summary>
        public static string StatoLegno {
            get {
                return ResourceManager.GetString("StatoLegno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Strati.
        /// </summary>
        public static string Strati {
            get {
                return ResourceManager.GetString("Strati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tipo.
        /// </summary>
        public static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tipo Pacco.
        /// </summary>
        public static string TipoPacco {
            get {
                return ResourceManager.GetString("TipoPacco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unità Misura Prezzo Acquisto.
        /// </summary>
        public static string UnitaMisuraPrezzoAcquisto {
            get {
                return ResourceManager.GetString("UnitaMisuraPrezzoAcquisto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
    }
}
